apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
  namespace: notes-namespace
data:
  init-db.sql: |
    CREATE DATABASE notes;
    \c notes
    CREATE TABLE IF NOT EXISTS notes (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        content TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
